/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Automation(props) { 
  const { nodes, materials } = useGLTF("/models/Automation.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve049.geometry}
        material={materials.Dragon_Main}
        position={[-2.166, -1.537, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve048.geometry}
        material={materials.Dragon_Main}
        position={[-2.166, -1.537, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve026.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve025.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve024.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve023.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve022.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve021.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve020.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve019.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve018.geometry}
        material={materials.Dragon_Main}
        position={[-2.491, -2.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.829}
      />
    </group>
  );
}

useGLTF.preload("/models/Automation.glb");