/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GreenEnergy(props) {
  const { nodes, materials } = useGLTF("/models/GreenEnergy.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve083.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve082.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve081.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve080.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve079.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve078.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve077.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve076.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve075.geometry}
        material={materials.Dragon_Main}
        position={[-2.463, -1.473, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={20.373}
      />
    </group>
  );
}

useGLTF.preload("/models/GreenEnergy.glb");