/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Manufactoring(props) {
  const { nodes, materials } = useGLTF("/models/Manufactoring.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve113.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve112.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve111.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve110.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve109.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve108.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve107.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve106.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve105.geometry}
        material={materials.Dragon_Main}
        position={[-2.182, -1.667, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.049}
      />
    </group>
  );
}

useGLTF.preload("/models/Manufactoring.glb");