/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Poultry(props) {
  const { nodes, materials } = useGLTF("/models/Poultry.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve122.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve121.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve120.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve119.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve118.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve117.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve116.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve115.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve114.geometry}
        material={materials.Dragon_Main}
        position={[-2.373, -0.873, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.794}
      />
    </group>
  );
}

useGLTF.preload("/models/Poultry.glb");