/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Systeel(props) {
  const { nodes, materials } = useGLTF("/models/systeel.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve166.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve165.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve164.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve163.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve162.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve161.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve160.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve159.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve158.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve157.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve156.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve155.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve154.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve153.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve152.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve151.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve150.geometry}
        material={materials.Dragon_Main}
        position={[-1.593, -0.731, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.05}
      />
    </group>
  );
}

useGLTF.preload("/models/systeel.gltf");